### ISSUE TITLE
bam files from nanopore RRMS data and Methylbed file for methylartist

### ISSUE THREAD

**Issue by foxchase** [adamewing/methylartist#28] opened 2022-09-14 15:13 UTC
Sorry to bother you two questions below.
1. I downloaded the RRMS bam files from nanopore and these bam files were generated with remora. And I tried to plot a entire chromosome 22 and got an error, mod bam formatting error,  pls see attached.
![ksnip_20220914-110327](https://user-images.githubusercontent.com/28757518/190193387-c4c95cea-32aa-4e0c-a3e8-f369e2eac4b4.png)
2. Is it possible to use Methybed file for Methylartist?

Thank you in advance!

**Comment by adamewing** [comment] 2022-09-16 21:40
1. Is this a publicly available .bam file I could download from somewhere?
2. methylartist can generate bed bedMethyl files via `wgmeth` but they're not usable as input as they don't contain per-read information.

**Comment by foxchase** [comment] 2022-09-16 21:52
Thanks for your reply. Yes, the link below for RRMS data 
https://labs.epi2me.io/rrms2022.07/

**Comment by adamewing** [comment] 2022-09-19 06:00
I was able to replicate this via the .bam file `s3://ont-open-data/rrms_2022.07/basecalling/bonito_remora/Benchmarking_ASmethylation_COLO829BL_1-5/COLO829BL_1/bonito_calls.bam`. The cause is when there are no methylation sites in a read and a likelihood of methylation is given e.g. `MM:Z:   ML:B:C,0`, which seems to be incorrect based on my reading of the SAM optional tags spec. In any case it's easy enough to ignore reads with no methylation calls which side-steps the issue. Should be fixed with commit 655a4c.

**Closed** 2022-09-21 15:47 UTC
